version: "3.7"

services:
  db:
    image: mysql
    restart: always
    ports:
      - "3300:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Tlmm3PjdJ*
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build:
      context: .  # Dockerfile이 있는 디렉토리
      dockerfile: Dockerfile  # 사용할 Dockerfile 지정 (옵션)
    ports:
      - "8000:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
